version: "3"

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./data/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./data/certs/pihole.crt:/etc/ssl/certs/pihole.crt
      - ./data/certs/pihole.key:/etc/ssl/private/pihole.key
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/sites-enabled/:/etc/nginx/sites-enabled/
    networks:
      backend:
        ipv4_address: "172.31.0.110"
      frontproxy: {}

    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      DHCP_ACTIVE: "true"
      DHCP_START: 192.168.8.10
      DHCP_END: 192.168.8.100
      DHCP_ROUTER: 192.168.8.1
      DNSMASQ_LISTENING: all
      PIHOLE_DOMAIN: home.lan
      PIHOLE_DNS_: 1.1.1.1, 8.8.8.8
      ServerIP: 192.168.8.2
      TZ: Australia/Sydney
      VIRTUAL_HOST: pihole.home.lan
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - ./data/dnsmasq.d/:/etc/dnsmasq.d/
      - ./data/pihole/:/etc/pihole
    cap_add:
      - NET_ADMIN
    depends_on:
      - dhcphelper
    networks:
      backend:
        ipv4_address: "172.31.0.100"
      frontproxy: {}
    restart: unless-stopped

  dhcphelper:
    container_name: dhcphelper
    build: ./dhcp-helper
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  frontproxy:
    external: true
