version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - ./data/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    - ./data/certs/pihole.crt:/etc/ssl/certs/pihole.crt
    - ./data/certs/pihole.key:/etc/ssl/private/pihole.key
    - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./data/nginx/sites-enabled/:/etc/nginx/sites-enabled/
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    environment:
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.8.10
      DHCP_END: 192.168.8.100
      DHCP_ROUTER: 192.168.8.1
      PIHOLE_DOMAIN: home.lan
      PIHOLE_DNS_: 1.1.1.1, 8.8.8.8
      ServerIP: 192.168.8.2
      TZ: Australia/Sydney
      VIRTUAL_HOST: pihole.home.lan
    volumes:
    - ./data/etc-pihole/:/etc/pihole/
    - ./data/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
